fruits=["Apple","Banana","Grapes","Mango","Pineapple","Blueberries"]
print(fruits)
print(fruits[2])
print(fruits[1:4])
print("Length o list is : ",len(fruits))
fruits.append("jackfruit")
print("After apending :",fruits)
fruits.insert(1,"Strawberry")
print("After insert operation",fruits)
fruits.pop()
print("After pop operation",fruits)
fruits.remove("Banana")
print("After remove operation",fruits)
fruits.sort()
print("After sort operation",fruits)
fruits.reverse()
print("After reverse operation",fruits)
